version: '3.8'

services:

  backend:

    build:
      context: ./backend

    container_name: erp-backend

    restart: always

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    volumes:
      - ./uploads:/app/uploads

  frontend:

    build:
      context: ./client

    container_name: erp-frontend

    restart: always

    ports:
      - "3000:80"

    depends_on:
      - backend