export  const allUnits = [
  { label: "Kilogram", value: "kg" },
  { label: "Gram", value: "g" },
  { label: "Milligram", value: "mg" },
  { label: "Tonne", value: "tonne" },
  { label: "Litre", value: "ltr" },
  { label: "Millilitre", value: "ml" },
  { label: "Cubic Meter", value: "cbm" },
  { label: "Cubic Centimeter", value: "cc" },
  { label: "Pieces", value: "pcs" },
  { label: "Box", value: "box" },
  { label: "Pack", value: "pack" },
  { label: "Dozen", value: "dozen" },
  { label: "Gross", value: "gross" },
  { label: "Meter", value: "m" },
  { label: "Centimeter", value: "cm" },
  { label: "Millimeter", value: "mm" },
  { label: "Inch", value: "inch" },
  { label: "Feet", value: "ft" },
  { label: "Yard", value: "yd" },
  { label: "Square Meter", value: "sqm" },
  { label: "Square Feet", value: "sqft" },
  { label: "Roll", value: "roll" },
  { label: "Bag", value: "bag" },
  { label: "Bundle", value: "bundle" },
  { label: "Pair", value: "pair" },
  { label: "Set", value: "set" },
  { label: "Tray", value: "tray" },
  { label: "Can", value: "can" },
  { label: "Bottle", value: "bottle" },
  { label: "Jar", value: "jar" },
  { label: "Tube", value: "tube" },
  { label: "Carton", value: "carton" },
  { label: "Drum", value: "drum" },
  { label: "Barrel", value: "barrel" },
  { label: "Sachet", value: "sachet" },
  { label: "Strip", value: "strip" },
  { label: "Tablet", value: "tablet" },
  { label: "Capsule", value: "capsule" },
  { label: "Hour", value: "hr" },
  { label: "Minute", value: "min" },
  { label: "Second", value: "sec" }
];
