export interface MenuItem {
  heading?: string;
  name?: string;
  icon?: any;
  id?: number;
  to?: string;
  items?: MenuItem[];
  children?: any;
  url?: any;
  subId?:any;
  add?: any;
  view?: any;
  edit?: any;
  delete?: any;
}

import { uniqueId } from "lodash";


const SidebarContent: MenuItem[] = [
  
  {
    id: 1,
    name: "Dashboard",
    items: [
      {
        heading: "Dashboard",
        children: [
          {
            name: "Dashboard",
            icon: "carbon:report",
            id: uniqueId(),
            url: "/",
            subId:1,
              add: false,
           view: false,
           edit: false,
           delete: false,
            
          },
          // {
          //   name: "Permission",
          //   icon: "arcticons:permissionsmanager",
          //   id: uniqueId(),
          //   url: "/permission",
          // }
        ],
      },
    ],
  },
  
   {
    id: 2,
    name: "inventory Managment",
    items: [
      {
        heading: "inventory Managment",
         children: [
             {
            subId:1,
            name: "Inbound Gate Entry",
            icon: "ph:user-circle-check-thin",
            id: uniqueId(),
            url: "/inventory/check-in",
             add: false,
           view: false,
          edit: false,
             delete: false,
          },
          {
             subId:2,
            name: "Store Verification",
            icon: "basil:app-store-outline",
            id: uniqueId(),
            url: "/inventory/store",
             add: false,
            view: false,
            edit: false,
            delete: false,
          },

          {
        subId: 2,
        name: "BMR",
        icon: "carbon:ibm-gcm",
        id: uniqueId(),
        url: "/inventory/bmr",
        add: false,
        view: false,
        edit: false,
        delete: false,

      
        children: 
        [
          {
            subId: 1,
            name: "BMR Creation",
         icon: "carbon:document-add",
            id: uniqueId(),
            url: "/inventory/bmr/create",
            add: false,
            view: false,
            edit: false,
            delete: false,
          },  
    //       {
    //         subId: 2,
    //         name: "Line Clearance Dispensing",
    // icon: "carbon:task-complete",
    //         id: uniqueId(),
    //         url: "/inventory/bmr/line-clearance",
    //         add: false,

    //         view: false,
    //         edit: false,
    //         delete: false,
    //       },          
        ]
      },

          {
            subId:3,
            name: "QA/QC Inspection",
            icon: "token:qrdo",
            id: uniqueId(),
            url: "/inventory/qc",
            add: false,
            view: false,
            edit: false,
            delete: false,
          },

           {
            subId:4,
            name: "QA Batch Number",
            icon: "material-symbols:batch-prediction-outline-sharp",
            id: uniqueId(),
            url: "/inventory/qc-batch",
            add: false,
            view: false,
            edit: false,
            delete: false,
          },

           {
            subId:5,
            name: "Production",
            icon: "fluent:production-20-filled",
            id: uniqueId(),
            url: "/inventory/production",
             add: false,
        view: false,
        edit: false,
        delete: false,
          },

          {
            subId:6,
            name: "Finish",
            icon: "fluent:check-20-filled",
            id: uniqueId(),
            url: "/inventory/finishing",
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
              {
            subId:7,
            name: "QA/QC Approval",
            icon: "material-symbols:batch-prediction-outline-sharp",
            id: uniqueId(),
            url: "/inventory/qa-qc-approval",
             add: false,
              view: false,
              edit: false,
              delete: false,
          },
          {
            subId:7,
            name: "FPR",
            icon: "material-symbols:batch-prediction-outline-sharp",
            id: uniqueId(),
            url: "/inventory/fpr",
             add: false,
              view: false,
              edit: false,
              delete: false,
          },
          
          {
            subId:7,
            name: "Dispatch",
            icon: "mdi:disc",
            id: uniqueId(),
            url: "/inventory/dispatch",
            add: false,
            view: false,
            edit: false,
            delete: false,
          }
        ]
      },
    ],
  },
     {
    id: 3,
    name: "Master",
    items: [
      {
        heading: "Master",
        children: [
          
          {
            name: "Company",
            icon: "ix:customer",
            id: uniqueId(),
            url: "/master/company",
            subId:1,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
          {
            name: "Supplier",
            icon: "streamline-freehand:business-product-supplier-2",
            id: uniqueId(),
            url: "/master/supplier",
            subId:2,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
          {
            name: "Customer",
            icon: "ix:customer",
            id: uniqueId(),
            url: "/master/customer",
            subId:3,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
      
           {
            name: "Accounts",
            icon: "mdi:account-key-outline",
            id: uniqueId(),
            url: "/master/accounts",
            subId:5,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
          {
            name: "Packing Material",
            icon: "lsicon:packing-box-outline",
            id: uniqueId(),
            url: "/master/packing-material",
            subId:6,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
          {
            name: "Transport",
            icon: "icon-park-outline:transporter",
            id: uniqueId(),
            url: "/master/transport",
            subId:7,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
           {
            name: "Batch Master",
            icon: "lsicon:batch-add-outline",
            id: uniqueId(),
            url: "/master/batch-masters",
            subId:8,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
           {
            name: "Pending Order",
            icon: "material-symbols:pending-outline",
            id: uniqueId(),
            url: "/master/pending-orders",
            subId:9,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
           {
            name: "Stock Master",
            icon: "lsicon:management-stockout-outline",
            id: uniqueId(),
            url: "/master/stock-masters",
            subId:10,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
          {
            name: "Sales Master",
            icon: "iconoir:home-sale",
            id: uniqueId(),
            url: "/master/sales-masters",
            subId:11,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
           {
            name: "HSN Master",
            icon: "mdi:signal-hspa",
            id: uniqueId(),
            url: "/master/hsn-masters",
            subId:12,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
          {
            name: "Currency",
            icon: "ri:currency-line",
            id: uniqueId(),
            url: "/master/currency-master",
            subId:13,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
           {
            name: "Equipment",
            icon: "lsicon:equipment-outline",
            id: uniqueId(),
            url: "/master/equipment",
            subId:14,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
          {
            name: "RM Code",
            icon: "file-icons:codeship",
            id: uniqueId(),
            url: "/master/rm-code",
            subId:15,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
          {
            name: "PM Code",
            icon: "file-icons:codeship",
            id: uniqueId(),
            url: "/master/pm-code",
            subId:16,
             add: false,
              view: false,
              edit: false,
              delete: false,
          },
          {
            name: "Units",
            icon: "material-symbols:ac-unit-rounded",
            id: uniqueId(),
            url: "/master/unit",
            subId:17,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
          {
            name: "Designation",
            icon: "hugeicons:manager",
            id: uniqueId(),
            url: "/master/designation",
            subId:18,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
          {
            name: "Qualification",
            icon: "healthicons:i-exam-qualification-outline",
            id: uniqueId(),
            url: "/master/qualification",
            subId:19,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
           {
            name: "Make Master",
            icon: "eos-icons:state",
            id: uniqueId(),
            url: "/master/make-masters",
            subId:20,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
          {
            name: "Department Master",
            icon: "icon-park-outline:city",
            id: uniqueId(),
            url: "/master/department-masters",
            subId:31,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
           {
            name: "Staff Master",
            icon: "icon-park-outline:file-staff",
            id: uniqueId(),
            url: "/master/staff-master",
            subId:21,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
          {
            name: "State",
            icon: "eos-icons:state",
            id: uniqueId(),
            url: "/master/states",
            subId:22,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
          {
            name: "City",
            icon: "icon-park-outline:city",
            id: uniqueId(),
            url: "/master/cites",
            subId:23,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
           {
            name: "Inward ",
            icon: "fluent:arrow-move-inward-20-filled",
            id: uniqueId(),
            url: "/master/inward",
            subId:24,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
           {
            name: "Outward ",
            icon: "material-symbols:arrow-outward-rounded",
            id: uniqueId(),
            url: "/master/outward",
            subId:25,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
           {
            name: "Purchase",
            icon: "bx:purchase-tag",
            id: uniqueId(),
            url: "/master/purchase",
            subId:26,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
           {
            name: "BMR",
            icon: "carbon:ibm-gcm",
            id: uniqueId(),
            url: "/master/bmr",
            subId:27,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
           {
            name: "Finish Good",
            icon: "ep:finished",
            id: uniqueId(),
            url: "/master/finish-good",
            subId:28,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
          {
            name: "Formula",
            icon: "fluent:clipboard-math-formula-24-regular",
            id: uniqueId(),
            url: "/master/formula",
            subId:29,
             add: false,
        view: false,
        edit: false,
        delete: false,
          },
           {
            name: "Export Document",
            icon: "mi:document",
            id: uniqueId(),
            url: "/master/document",
            subId:30,
             add: false,
        view: false,
        edit: false,
        delete: false,
          }
        ],
      },
    ],
     },
];

export default SidebarContent;
